export const DummyProducts = [
  {
    id: 1,
    img: "https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/coffee-asorted.jpg",
    category: "Groceries",
    name: "Assorted Coffee",
    desc: "Neque porro quisquam est, qui dolore ipsum quia dolor sit amet, consectetur adipisci velit, sed quia non incidunt lores ta porro ame. numquam eius modi tempora incidunt lores ta porro ame.",
    rating: 0,
    price: 35.0,
    sale: false,
    bestSelling: true,
    trending: true,
  },
  {
    id: 2,
    img: "https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/sanitizer-300x300.jpg",
    category: "Groceries",
    name: "Hand Sanitizer",
    desc: "Neque porro quisquam est, qui dolore ipsum quia dolor sit amet, consectetur adipisci velit, sed quia non incidunt lores ta porro ame. numquam eius modi tempora incidunt lores ta porro ame.",
    rating: 0,
    price: 15.0,
    sale: false,
    bestSelling: true,
    trending: true,
  },
  {
    id: 3,
    img: "https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/red-chillies-300x300.jpg",
    category: "Groceries",
    name: "Handpicked Red Chillies",
    desc: "Neque porro quisquam est, qui dolore ipsum quia dolor sit amet, consectetur adipisci velit, sed quia non incidunt lores ta porro ame. numquam eius modi tempora incidunt lores ta porro ame.",
    rating: 0,
    price: 19.0,
    sale: false,
    bestSelling: true,
    trending: true,
  },
  {
    id: 4,
    img: "https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/edible-oil-300x300.jpg",
    category: "Groceries",
    name: "Natural Extracted Edible Oil",
    desc: "Neque porro quisquam est, qui dolore ipsum quia dolor sit amet, consectetur adipisci velit, sed quia non incidunt lores ta porro ame. numquam eius modi tempora incidunt lores ta porro ame.",
    rating: 0,
    price: 25.0,
    sale: true,
    bestSelling: true,
    trending: false,
  },
  {
    id: 5,
    img: "https://websitedemos.net/organic-shop-02/wp-content/uploads/sites/465/2018/06/orage-juice-kariz-300x300.jpg",
    category: "Juice",
    name: "Fresh Orange Juice",
    desc: "Neque porro quisquam est, qui dolore ipsum quia dolor sit amet, consectetur adipisci velit, sed quia non incidunt lores ta porro ame. numquam eius modi tempora incidunt lores ta porro ame.",
    rating: 0,
    price: 18.0,
    sale: false,
    bestSelling: false,
    trending: true,
  },
];
